
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#customize: !include customize.yaml

cover: !include includes/covers.yaml

climate:
  - platform: generic_thermostat
    name: studioigor
    heater: switch.zona_riscaldamento_studio
    target_sensor: sensor.temperature_studio
    min_temp: 15
    max_temp: 21
    target_temp: 19
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

  - platform: generic_thermostat
    name: madda
    heater: switch.zona_riscaldamento_madda
    target_sensor: sensor.temperature_madda
    min_temp: 15
    max_temp: 22
    target_temp: 20
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

  - platform: generic_thermostat
    name: bagnomadda
    heater: switch.zona_riscaldamento_bagno
    target_sensor: sensor.temperature_bagnomadda
    min_temp: 15
    max_temp: 21
    target_temp: 19
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

  - platform: generic_thermostat
    name: cucina
    heater: switch.zona_riscaldamento_cucina
    target_sensor: sensor.temperature_cucina
    min_temp: 15
    max_temp: 23
    target_temp: 20
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

  - platform: generic_thermostat
    name: design
    heater: switch.zona_riscaldamento_sala
    target_sensor: sensor.temperature_design
    min_temp: 15
    max_temp: 22
    target_temp: 19
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

  - platform: generic_thermostat
    name: pianoterra
    heater: switch.zona_riscaldamento_pianoterra
    target_sensor: sensor.temperature_pianoterra
    min_temp: 15
    max_temp: 21
    target_temp: 19
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

  - platform: generic_thermostat
    name: primopiano
    heater: switch.zona_riscaldamento_primopiano
    target_sensor: sensor.temperature_primopiano
    min_temp: 15
    max_temp: 21
    target_temp: 19
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3


device_tracker:
  - platform: unifi_direct
    host: 192.168.1.161
      #port: 8443
      #verify_ssl: false
    username: !secret unifi_username
    password: !secret unifi_password

alarm_control_panel:
  - platform: manual
    name: "Antifurto!"
    code: !secret code_password
    delay_time: 15
    trigger_time: 1
    disarm_after_trigger: false


switch:
 - platform: relaymaster
   url: http://192.168.1.101
   username: !secret scheda101_username
   password: !secret scheda101_password
 - platform: relaymaster
   url: http://192.168.1.102
   username: !secret scheda102_username
   password: !secret scheda102_password
 - platform: relaymaster
   url: http://192.168.1.103
   username: !secret scheda103_username
   password: !secret scheda103_password
 - platform: relaymaster
   url: http://192.168.1.104
   username: !secret scheda104_username
   password: !secret scheda104_password
 - platform: relaymaster
   url: http://192.168.1.105
   username: !secret scheda105_username
   password: !secret scheda105_password
 - platform: relaymaster
   url: http://192.168.1.106
   username: !secret scheda106_username
   password: !secret scheda106_password
 - platform: relaymaster
   url: http://192.168.1.107
   username: !secret scheda107_username
   password: !secret scheda107_password
 - platform: relaymaster
   url: http://192.168.1.108
   username: !secret scheda108_username
   password: !secret scheda108_password
 - platform: relaymaster
   url: http://192.168.1.109
   username: !secret scheda109_username
   password: !secret scheda109_password


# - platform: broadlink
#   host: 192.168.1.170
#   mac: '34:EA:34:B2:F3:90'
#   switches:
#     reciever:
#      friendly_name: 'Condizionatore'
#      command_on: 'JgAaABweOR4bHhwdHB4dHRw6HhsdHR0dOTocAA0FAAAAAAAAAAAAAAAAAAA'
#      command_off: 'JgAaABweOR4bHhwdHB4dHRw6HhsdHR0dOTocAA0FAAAAAAAAAAAAAAAAAAA'

# inserisco controllo per SonOff eWelink che prevede accesso attraverso utente cloud e aggiunta dei componenti in /custom_components
#sonoff:
#  username: [!secret sonoff_email]
#  password: [!secret sonoff_password]
#  scan_interval: 60 #(optional, lower values than 60 won't work anymore!)
#  grace_period: 600 #(optional)
#  api_region: 'eu' #(optional)
#  entity_prefix: True #(optional)
#  debug: False #(optional)


binary_sensor:
 - platform: relaymaster
   url: http://192.168.1.101
   username: !secret scheda101_username
   password: !secret scheda101_password
 - platform: relaymaster
   url: http://192.168.1.102
   username: !secret scheda102_username
   password: !secret scheda102_password
 - platform: relaymaster
   url: http://192.168.1.103
   username: !secret scheda103_username
   password: !secret scheda103_password
 - platform: relaymaster
   url: http://192.168.1.104
   username: !secret scheda104_username
   password: !secret scheda104_password
 - platform: relaymaster
   url: http://192.168.1.105
   username: !secret scheda105_username
   password: !secret scheda105_password
 - platform: relaymaster
   url: http://192.168.1.106
   username: !secret scheda106_username
   password: !secret scheda106_password
 - platform: relaymaster
   url: http://192.168.1.107
   username: !secret scheda107_username
   password: !secret scheda107_password
 - platform: relaymaster
   url: http://192.168.1.108
   username: !secret scheda108_username
   password: !secret scheda108_password
 - platform: relaymaster
   url: http://192.168.1.109
   username: !secret scheda109_username
   password: !secret scheda109_password


sensor:
 - platform: relaymaster
   url: http://192.168.1.101
   username: !secret scheda101_username
   password: !secret scheda101_password
 - platform: relaymaster
   url: http://192.168.1.102
   username: !secret scheda102_username
   password: !secret scheda102_password
 - platform: relaymaster
   url: http://192.168.1.103
   username: !secret scheda103_username
   password: !secret scheda103_password
 - platform: relaymaster
   url: http://192.168.1.105
   username: !secret scheda105_username
   password: !secret scheda105_password
 - platform: relaymaster
   url: http://192.168.1.106
   username: !secret scheda106_username
   password: !secret scheda106_password
 - platform: relaymaster
   url: http://192.168.1.107
   username: !secret scheda107_username
   password: !secret scheda107_password


 - platform: template
   sensors:
     temperature_primopiano:
       #  entity_id: sensor.sonda_p1
          value_template: '{{ states.sensor.sonda_p1.state|float / 10 }}'
          friendly_name: 'Temperatura Primo Piano'
          unit_of_measurement: '°C'
 - platform: template
   sensors:
     temperature_pianoterra:
       #entity_id: sensor.sonda_p0
        value_template: '{{ states.sensor.sonda_p0.state|float / 20 }}'
        friendly_name: 'Temperatura Piano Terra'
        unit_of_measurement: '°C'

 - platform: template
   sensors:
     temperature_madda:
       #   entity_id: sensor.sonda_madda
        value_template: '{{ states.sensor.sonda_madda.state|float / 20 }}'
        friendly_name: 'Temperatura Madda'
        unit_of_measurement: '°C'

 - platform: template
   sensors:
      temperature_studio:
        #entity_id: sensor.sonda_studio
        value_template: '{{ states.sensor.sonda_studio.state|float / 20 }}'
        friendly_name: 'Temperatura Studio Igor'
        unit_of_measurement: '°C'

 - platform: template
   sensors:
      temperature_bagnomadda:
        #entity_id: sensor.sonda_bagno
        value_template: '{{ states.sensor.sonda_bagno.state|float / 10 }}'
        friendly_name: 'Temperatura Bagno Madda'
        unit_of_measurement: '°C'

 - platform: template
   sensors:
      temperature_cucina:
        #entity_id: sensor.sonda_cucina
        value_template: '{{ states.sensor.sonda_cucina.state|float / 20 }}'
        friendly_name: 'Temperatura Cucina'
        unit_of_measurement: '°C'

 - platform: template
   sensors:
      temperature_design:
        #entity_id: sensor.sonda_design
        value_template: '{{ states.sensor.sonda_design.state|float / 20 }}'
        friendly_name: 'Temperatura Sala Design'
        unit_of_measurement: '°C'

 - platform: time_date
   display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
    - 'beat'
